### ISSUE TITLE
Gradle wrapper error (tested on linux)

### ISSUE THREAD

**Issue by achjaj** [Grouter/flocking#1]
When I run gradlew script on my Linux machine, I got this error:
`Exception in thread "main" java.lang.RuntimeException: Wrapper properties file 'gradle/wrapper/gradle-wrapper.properties' does not exist.`

**Comment by Grouter** [comment]
Uploaded gradle-wrapper.properties. Pull and try again.

**Comment by achjaj** [comment]
It works.
